# Generated by Django 3.2.3 on 2021-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='thingId',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
