# Generated by Django 3.2.3 on 2021-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0002_donation_thingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
