# Generated by Django 3.2.3 on 2021-09-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0005_auto_20210907_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(default=None, null=True),
        ),
    ]
