# Generated by Django 3.2.3 on 2021-09-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0007_alter_donation_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='adult',
            new_name='participate',
        ),
    ]
