# Generated by Django 3.2.3 on 2021-09-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucket_view', '0008_rename_adult_donation_participate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significance', models.BooleanField(default=False)),
                ('curiosity', models.BooleanField(default=False)),
                ('researcher', models.BooleanField(default=False)),
                ('participate', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bucket_view.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
