# Generated by Django 3.2.3 on 2022-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0009_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_ext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
