# Generated by Django 3.2.3 on 2022-04-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0011_awareness'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.BooleanField(default=False)),
                ('takeout', models.BooleanField(default=False)),
                ('goal', models.CharField(default=None, max_length=200, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bucket_view.donation')),
            ],
        ),
    ]
