# Generated by Django 3.2.3 on 2022-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_view', '0012_initialawareness'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.CharField(default=None, max_length=1, null=True)),
                ('types', models.CharField(default=None, max_length=1, null=True)),
                ('duration', models.CharField(default=None, max_length=1, null=True)),
                ('decision', models.CharField(default=None, max_length=1, null=True)),
                ('learn', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
