# Generated by Django 3.2.3 on 2021-07-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description_tweet', models.CharField(max_length=280, null=True)),
                ('description', models.TextField(null=True)),
                ('data', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('active', models.BooleanField(default=False, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('contact_name', models.CharField(max_length=100, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('data_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('data', models.ImageField(blank=True, null=True, upload_to='data/%Y/%m/%d')),
                ('available', models.BooleanField(default=False, null=True)),
                ('updates', models.BooleanField(default=False, null=True)),
                ('authorize', models.BooleanField(default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='causes.cause')),
            ],
        ),
    ]
