# Generated by Django 3.1.6 on 2021-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_auto_20210222_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='technology',
            new_name='data',
        ),
        migrations.AddField(
            model_name='cause',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
