# Generated by Django 3.1.6 on 2021-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='description_tweet',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
