# Generated by Django 3.1.6 on 2021-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0006_cause_data_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='authorize',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='updates',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
