# Generated by Django 3.1.6 on 2021-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0007_auto_20210226_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='data/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
