# Generated by Django 3.2.3 on 2021-06-04 14:37

import bucket.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('sid', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', bucket.managers.BucketUserManager()),
            ],
        ),
    ]
