# Generated by Django 3.2.3 on 2021-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketuser',
            name='user_id',
            field=models.CharField(default=None, max_length=60, unique=True),
        ),
    ]
