# Generated by Django 3.2.3 on 2021-06-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_auto_20210624_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2token',
            name='name',
        ),
    ]
